-- Create sequences for Visitor and Exhibitor tables
CREATE SEQUENCE visitor_seq START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE exhibitor_seq START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
-- Add more sequences as needed for other tables
-- Example:
-- CREATE SEQUENCE tradefair_seq START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
-- CREATE SEQUENCE hall_seq START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
-- CREATE SEQUENCE stall_seq START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
-- CREATE SEQUENCE ticket_seq START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
-- CREATE SEQUENCE feedback_seq START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;